# Generated by Django 5.2.14 on 2026-06-09 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Рік')),
                ('price_usd', models.PositiveIntegerField(verbose_name='Ціна ($)')),
                ('mileage_km', models.PositiveIntegerField(verbose_name='Пробіг (тис. км)')),
                ('fuel', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ/Бензин'), ('electric', 'Електро'), ('hybrid', 'Гібрид')], default='petrol', max_length=20, verbose_name='Паливо')),
                ('engine_volume', models.DecimalField(decimal_places=2, max_digits=4, verbose_name="Об'єм двигуна (л)")),
                ('transmission', models.CharField(choices=[('auto', 'Автомат'), ('manual', 'Механіка'), ('robot', 'Робот'), ('variator', 'Варіатор')], default='auto', max_length=20, verbose_name='КПП')),
                ('drive', models.CharField(choices=[('fwd', 'Передній'), ('rwd', 'Задній'), ('awd', 'Повний')], default='fwd', max_length=10, verbose_name='Привід')),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Позашляховик / Кросовер'), ('hatchback', 'Хетчбек'), ('wagon', 'Універсал'), ('coupe', 'Купе'), ('minivan', 'Мінівен'), ('pickup', 'Пікап'), ('convertible', 'Кабріолет')], default='sedan', max_length=20, verbose_name='Тип кузова')),
                ('color', models.CharField(default='Чорний', max_length=50, verbose_name='Колір')),
                ('city', models.CharField(default='Київ', max_length=100, verbose_name='Місто')),
                ('region', models.CharField(default='Київська', max_length=100, verbose_name='Область')),
                ('description', models.TextField(blank=True, verbose_name='Опис від продавця')),
                ('vin_code', models.CharField(blank=True, max_length=17, verbose_name='VIN-код')),
                ('license_plate', models.CharField(blank=True, max_length=15, verbose_name='Держ. номер')),
                ('owners_count', models.PositiveIntegerField(default=1, verbose_name='Кількість власників')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Перевірено')),
                ('is_first_registration', models.BooleanField(default=False, verbose_name='Перша реєстрація')),
                ('imported_from', models.CharField(blank=True, max_length=100, verbose_name='Пригнано з')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Перегляди')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Продавець')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/photos/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.car')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('is_verified_seller', models.BooleanField(default=False, verbose_name='Перевірений продавець')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': 'Профілі',
            },
        ),
        migrations.CreateModel(
            name='SavedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='main.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Збережене авто',
                'verbose_name_plural': 'Збережені авто',
                'unique_together': {('user', 'car')},
            },
        ),
    ]
